---
- name: start firewalld
  systemd:
    name: firewalld
    state: started

- name: firewalld setting
  firewalld: port={{ item }} permanent=true state=enabled immediate=true
  with_items:
    - "80/tcp"
    - "443/tcp"
    - "6443/tcp"
    - "2379-2380/tcp"
    - "10250-10256/tcp"
    - "30000-32767/tcp"
    - "8472/udp"

- name: disable swap
  command: swapoff -a